service: user-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: us-east-1

functions:
  createUser:
    handler: app.create_user
    events:
      - http:
          path: users
          method: post
          cors: true

  getUserById:
    handler: app.get_user_by_id
    events:
      - http:
          path: users/{userId}
          method: get
          cors: true

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
